### ISSUE TITLE
Indexed in Google checker fails when the AMP page is over HTTP

### ISSUE THREAD

**Issue by oliverfernandez** [ampproject/ampbench#51] opened 2018-05-31 09:00 UTC
When the AMP page is over HTTP, like [this one](http://amp.ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened), "Indexed in Google" checker fails because it also tries to find the URL in the AMP cache using HTTP, which is incorrect.

Since URLs in AMP Cache are always HTTPs, this checker should check the following URL
`https://amp.ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened`

instead of this one

`http://amp.ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened`

**Comment by dakkad** [comment] 2018-08-30 15:07
Hi Oliver,

I had a quick look at your [canonical page](https://ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened) for the example [AMP page](http://amp.ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened) that you mentioned. 

You currently have the http version of the AMP page linked from the canonical:

<link rel="amphtml" href="http://amp.ewn.co.za/2018/05/31/mokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened">

When I tried [testing the https version](https://ampbench.appspot.com/validate?url=https%3A%2F%2Famp.ewn.co.za%2F2018%2F05%2F31%2Fmokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-openeds) of your AMP content it seems that the sub-domain doesn't currently have support for https.

From the [AMP caching](https://www.ampproject.org/docs/fundamentals/how_cached) guidance it seems to be the case that as the canonical page exposes a http AMP page that the cache would store the http version. 

I think this may be working as intended but would like some clarification about the difference in expected behaviour if you could.

Thanks,

**Comment by oliverfernandez** [comment] 2018-08-31 09:56
Hello @dakkad ,

The AMP cache never exposes http URLs, no matter if the original AMP page is under http or https. That's why I think AMPBench should always try to look for https URL in the AMP cache.

For both http and https AMP pages, there's always a valid https version in the AMP cache

**Comment by ithinkihaveacat** [comment] 2018-09-06 16:28
Seems to be fixed now:

https://ampbench.appspot.com/validate?url=http%3A%2F%2Famp.ewn.co.za%2F2018%2F05%2F31%2Fmokholo-report-on-r2-4bn-sa-express-fuel-deal-will-determine-if-case-is-opened

**Comment by oliverfernandez** [comment] 2018-09-06 16:39
@ithinkihaveacat Yes it is! Thanks :)

**Comment by pietergreyling** [comment] 2018-09-06 16:44
Thanks for verifying this, it was merged and deployed as per [this commit](https://github.com/ampproject/ampbench/commit/067a2265c47a241da4afbd029c1fe0f82ac2e248).

**Closed by pietergreyling** 2018-09-06 16:44 UTC
